# Generated by Django 4.1.5 on 2023-02-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('currency_date', models.DateField()),
                ('mid_rate', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
    ]
