# Generated by Django 4.1.5 on 2023-02-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('rate_date', models.DateField()),
                ('mid_rate', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Currences',
        ),
    ]
