# Generated by Django 4.1.5 on 2023-02-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_exchangerates_delete_currences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('inv_currency', models.CharField(max_length=3)),
                ('inv_date', models.DateField()),
                ('inv_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_date', models.DateField()),
                ('inv_amount_PLN', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField()),
            ],
        ),
    ]
