# Generated by Django 4.1.5 on 2023-03-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_invoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='inv_amount_PLN',
        ),
        migrations.AlterField(
            model_name='invoices',
            name='companyname',
            field=models.CharField(max_length=100, verbose_name='Company name:'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='inv_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Invoice amount:'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='inv_currency',
            field=models.CharField(max_length=3, verbose_name='Invoice currency:'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='inv_date',
            field=models.DateField(verbose_name='Invoice date:'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='is_paid',
            field=models.BooleanField(verbose_name='Is paid:'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='rate_date',
            field=models.DateField(verbose_name='Date of exchange rate:'),
        ),
    ]
