# Generated by Django 4.1.5 on 2023-03-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_remove_invoices_inv_amount_pln_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='inv_amount_PLN',
            field=models.DecimalField(decimal_places=2, default=99, max_digits=10),
            preserve_default=False,
        ),
    ]
