# Generated by Django 4.1.5 on 2023-03-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_invoices_inv_amount_pln'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
